import type { Metadata } from "next";

import styles from "./layout.module.css";

import "./reset.css";
import "./fonts.css";
import "./global.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="sans-serif">
			<body>
				<header className={styles.header}>
					<nav className={`container ${styles.nav}`}>
						<ul className={styles.links}>
							<li className={styles.link}>
								<a href="/">FussyCoder</a>
							</li>
							<li className={styles.link}>
								<a href="/features">Features</a>
							</li>
						</ul>
					</nav>
				</header>
				<main className="container">{children}</main>
				<footer></footer>
			</body>
		</html>
	);
}
